version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    entrypoint: '/app/docker/app/entrypoint.dev.sh'
    ports:
      - '8000:8000'
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app:cached
    command: poetry run ./manage.py runserver 0.0.0.0:8000
    environment:
      DB_NAME: 'playback_db'
      DB_USER: 'playback'
      DB_PASSWORD: 'docker'
      DB_HOST: 'db'
      DB_PORT: '3306'
  frontend:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    entrypoint: '/app/docker/frontend/entrypoint.dev.sh'
    ports:
      - '8080:8080'
    volumes:
        - .:/app:cached
    command: yarn run build --watch
  db:
    image: mysql:8.0.13
    volumes:
      - storage:/var/lib/mysql
      - ./docker/db/mysql-confd:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'playback'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: 'playback_db'
volumes:
  storage:

