version: '2'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/code:cached
    command: poetry run ./manage.py runserver 0.0.0.0:8000
  db:
    image: mysql:8.0.13
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
